In [1]:
import numpy as np
# 以 A+B來說

va = [1, 2, 3]
vb = [4, 5, 6]

va+vb

# 我們要這樣寫
va = [1, 2, 3]
vb = [4, 5, 6]

vc = list()
for i in range(len(va)):
    vc.append(va[i]+vb[i])
print(vc)

[5, 7, 9]


In [2]:
# 以numpy來處理
va1 = np.array(va)
vb1 = np.array(vb)
va1+vb1

array([5, 7, 9])

In [3]:
#乘法
va1*vb1

array([ 4, 10, 18])

In [5]:
#二維
a = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
    ])
a[1]

array([5, 6, 7, 8])

In [6]:
X = [1, 2, 3]
Y = np.array(X)
Y

array([1, 2, 3])

In [7]:
X

[1, 2, 3]

In [9]:
A = np.array([4, 5, 6])
A

array([4, 5, 6])

In [10]:
A.shape

(3,)

In [11]:
A.dtype

dtype('int32')

In [13]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros(3).dtype #預設

dtype('float64')

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.empty(2) #The function empty creates an array whose initial content is random and depends on the state of the mem

array([-5.64961235e-013, -2.32440255e-263])

In [18]:
np.arange(4) # 可以想像成是range(4)的numpy版

array([0, 1, 2, 3])

In [19]:
np.arange(2, 9, 2) # 也可以像 range那樣給(start, end, step)

array([2, 4, 6, 8])

In [20]:
np.linspace(0, 10, num=5) #to create an array with values that are spaced linearly in a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0, 10, num=20) #to create an array with values that are spaced linearly in a specified interval

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
x = np.ones(2, dtype=np.int64) #可以指定dtype的型態
x

array([1, 1], dtype=int64)

In [25]:
np.ones(2) #the default data type is floating point (np.float64)

array([1., 1.])

In [26]:
#sort操作
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
#array 運算
va = [1, 2, 3, 4]
vb = [5, 6, 7, 8]
va+vb

[1, 2, 3, 4, 5, 6, 7, 8]

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
a+b

array([ 6,  8, 10, 12])

In [32]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0) #與list 不同，必須要全部大小相同

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
#ndim, size, shape
array_example = np.array([
                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])


In [45]:
array_example.size #幾個元素

24

In [46]:
array_example.shape

(3, 2, 4)

In [47]:
#reshape
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [49]:
b = a.reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
#index, slice
data = np.array([1, 2, 3, 4, 5])

In [51]:
data[1]

2

In [52]:
data[0:4]

array([1, 2, 3, 4])

In [53]:
data[3:]

array([4, 5])

In [54]:
data[-4:4]

array([2, 3, 4])

In [55]:
data[-2]

4

In [56]:
#Broadcasting
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [57]:
v1 = np.array([1.0, 2.0])
v2 = np.array([1.6, 1.6])
v1*v2

array([1.6, 3.2])

In [58]:
#More useful array operations
data = np.array([4, 5, 6, 7, 8, 9, 10])
data.max()

10

In [59]:
data.min()

4

In [60]:
data.sum()

49

In [61]:
data.mean() #平均

7.0

In [62]:
data.prod() #連續乘

604800

In [75]:
#對上matrix的操作
a = np.array([[7, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()

11.40904526

In [69]:
a.mean()

0.4049648666666667

In [70]:
a.min()

0.05093587

In [76]:
#這邊很像excel中 column方向，或是row方向的操作
a.sum(axis=0)

array([7.67324943, 1.04875507, 1.01034462, 1.67669614])

In [77]:
a.sum(axis=1)

array([8.06779542, 1.55434556, 1.78690428])

In [78]:
a.mean(axis=0)

array([2.55774981, 0.34958502, 0.33678154, 0.55889871])

In [79]:
a.mean(axis=1)

array([2.01694885, 0.38858639, 0.44672607])

In [80]:
# TODO: 練習以這一個matrix進行sum, mean, min, max的操作
# 假設以下是一個班級學生的考試成績
#                國文, 數學
data = np.array([[80, 60], # A君
                 [85, 66], # B君
                 [90, 90], # C君
                 [70, 92], # D君
                 [82, 80]  # E君
                ])

In [82]:
#全班國文、數學平均
data.mean(axis=0)

array([81.4, 77.6])

In [86]:
#全班每位同學的總分
data.sum(axis=1)

180

In [87]:
#最高分
data.sum(axis=1).max() 

180

In [89]:
#進一步做比較
a = np.array([[1 , 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [93]:
#挑出a<5的項目
print(a[a < 5]) 

[1 2 3 4]


In [94]:
#用for 寫比較
m1 = [[1 , 2, 3, 4], 
      [5, 6, 7, 8], 
      [9, 10, 11, 12]]
for i in range(3):
    for j in range(4):
        if m1[i][j]<5:
            print(m1[i][j])

1
2
3
4


In [97]:
#可以被3整除
divisible_by_2 = a[a%3==0]
divisible_by_2

array([ 3,  6,  9, 12])

In [99]:
c = a[(a > 5) & (a%3==0)]
print(c)

[ 6  9 12]


In [101]:
#where,條件,保留補0
np.where(a%3==0, a, 0)

array([[ 0,  0,  3,  0],
       [ 0,  6,  0,  0],
       [ 9,  0,  0, 12]])

In [102]:
b = np.array([[1 , 1, 1, 1], 
              [1, 1, 1, 1], 
              [1, 1, 1, 1]])
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [103]:
#條件,a矩陣補b
np.where(a>5, a, b)

array([[ 1,  1,  1,  1],
       [ 1,  6,  7,  8],
       [ 9, 10, 11, 12]])